services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: pepa-linha

  rabbitmq:
    image: rabbitmq:3.10.1-management
    restart: always
    ports:
      - 5672:5672 # port for the queue
      - 15672:15672 # port for the in-browser manager

  nexus:
    image: sonatype/nexus3:3.52.0
    restart: always
    ports:
      - "8081:8081" # web portal port
      - "8082:8082" # port for the docker registry
      - "8083:8083" # port for the git system
