services:
  hutch.db:
    image: postgres
    restart: always
    ports:
      # don't expose the port to the database to the host machine
      - 5432
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - # .env file containing agent config variables; see https://github.com/link-lite/hutch/wiki/Configuration-(Production)#database

  hutch.msg_queue:
    image: rabbitmq:3.10.1-management
    restart: always
    ports:
      # don't expose the port to the msg queue to the host machine
      - 5672 # port for the queue
      - 15672:15672 # port for the in-browser manager
    volumes:
      - queue_data:/var/lib/rabbitmq/mnesia/
    env_file:
      - # .env file containing agent config variables; see https://github.com/link-lite/hutch/wiki/Configuration-(Production)#message-queue

  hutch.manager:
    image: # image for the manager
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - hutch.db
      - hutch.msg_queue
    env_file:
      - # .env file containing manager config variables; see https://github.com/link-lite/hutch/wiki/Configuration-(Production)#manager
    volumes:
      - # <path to local .pem and .key dir>:/certs:ro

  hutch.agent:
    image: # image for the manager
    restart: always
    depends_on:
      - hutch.db
      - hutch.msg_queue
      - hutch.manager
    env_file:
      - # .env file containing agent config variables; see https://github.com/link-lite/hutch/wiki/Configuration-(Production)#agent

volumes:
  db_data:
  queue_data:
