services:
  hutch.db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: pepa-linha

  hutch.msg_queue:
    image: rabbitmq:3.10.1-management
    restart: always
    ports:
      - 5672:5672 # port for the queue
      - 15672:15672 # port for the in-browser manager
    volumes:
      - queue_data:/var/lib/rabbitmq/mnesia/

  hutch.manager:
    build: app/HutchManager  # placeholder until image storage arranged
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - hutch.db
      - hutch.msg_queue

  hutch.agent:
    build: app/HutchAgent  # placeholder until image storage arranged
    restart: always
    depends_on:
      - hutch.db
      - hutch.msg_queue
      - hutch.manager

volumes:
  db_data:
  queue_data:
