services:
  hutch.db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: pepa-linha

  hutch.msg_queue:
    image: rabbitmq:3.10.1-management
    restart: always
    ports:
      - 5672:5672 # port for the queue
    volumes:
      - queue_data:/var/lib/rabbitmq/mnesia/

volumes:
  db_data:
  queue_data:
