---
- name: Install Docker
  hosts: tre_server
  handlers:
    - name: Reset connnection
      ansible.builtin.meta: reset_connection
  tasks:
    - name: Install Docker pre-requisites
      become: true
      ansible.builtin.apt:
        pkg:
          - ca-certificates
          - curl
          - gnupg
        update_cache: true

    - name: Ensure repository key is installed
      become: true
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      become: true
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install docker-ce
      become: true
      ansible.builtin.apt:
        name: docker-ce
        update_cache: true

    - name: Add user to docker group
      become: true
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        append: true
        groups:
          - docker
      register: user_added_to_docker
      notify:
        - Reset connnection

    - name: Install docker-compose
      become: true
      ansible.builtin.apt:
        name: docker-compose
        update_cache: true
