---
- name: Set up SSL
  hosts: tre_server
  tasks:
    - name: Generate an private key
      community.crypto.openssl_privatekey:
        path: "{{ ansible_env.HOME }}/key.pem"

    - name: Generate certificate signing request
      community.crypto.openssl_csr:
        path: "{{ ansible_env.HOME }}/crt.csr"
        privatekey_path: "{{ ansible_env.HOME }}/key.pem"
        common_name: workflowhub.eu

    - name: Generate self-signed certificate
      community.crypto.x509_certificate:
        path: "{{ ansible_env.HOME }}/cert.crt"
        privatekey_path: "{{ ansible_env.HOME }}/key.pem"
        csr_path: "{{ ansible_env.HOME }}/crt.csr"
        provider: selfsigned

    - name: Copy cert.crt to trust store
      become: true
      ansible.builtin.copy:
        src: "{{ ansible_env.HOME }}/cert.crt"
        dest: /usr/share/ca-certificates/cert.crt
        remote_src: true
        owner: root
        group: root
        mode: "0644"

    - name: Add cert.crt to /etc/ca-certificates.conf
      become: true
      ansible.builtin.lineinfile:
        path: /etc/ca-certificates.conf
        line: cert.crt

    - name: Update CA certificates
      become: true
      ansible.builtin.command:
        cmd: update-ca-certificates
