---
- name: Install WfExS
  hosts: tre_server
  tasks:
    - name: Clone WfExS
      ansible.builtin.git:
        repo: https://github.com/dcl10/WfExS-backend.git
        dest: "{{ ansible_env.HOME }}/WfExS-backend"
        version: 2648e3edf2dee3d4aad5984a5c5ca56824b4d585

    - name: WfExS virtual enviroment
      ansible.builtin.command:
        cmd: python3 -m venv .pyWEenv
        chdir: "{{ ansible_env.HOME }}/WfExS-backend"
        creates: "{{ ansible_env.HOME }}/WfExS-backend/.pyWEenv"

    - name: Install WfExS basic requirements
      ansible.builtin.command:
        cmd: ./full-installer.bash
        chdir: "{{ ansible_env.HOME }}/WfExS-backend"
