---
- name: Set up VM
  ansible.builtin.import_playbook: playbooks/set-up-vm.yml

- name: Set up SSL
  ansible.builtin.import_playbook: playbooks/set-up-ssl.yml

- name: Install Docker and Docker Compose
  ansible.builtin.import_playbook: playbooks/install-docker.yml

- name: Install Podman
  ansible.builtin.import_playbook: playbooks/install-podman.yml

- name: Install WfExS
  ansible.builtin.import_playbook: playbooks/wfexs.yml

- name: Install HutchAgent
  hosts: tre_server
  vars:
    hutch_version: v1.0.0-beta.2
    download_zip: "{{ ansible_env.HOME }}/hutch-{{ hutch_version }}.zip"
    install_dir: "{{ ansible_env.HOME }}/hutch-{{ hutch_version }}"
  tasks:
    - name: Download Hutch
      ansible.builtin.get_url:
        dest: "{{ download_zip }}"
        url: "https://github.com/HDRUK/hutch/releases/download/{{ hutch_version }}/hutch_linux-x64.zip"
        mode: "0644"
    - name: Make Install Directory
      ansible.builtin.file:
        path: "{{ install_dir }}"
        state: directory
        mode: "0644"
    - name: Unzip Hutch
      ansible.builtin.unarchive:
        src: "{{ download_zip }}"
        remote_src: true
        dest: "{{ install_dir }}"
    - name: Update Program Permissions
      ansible.builtin.file:
        path: "{{ install_dir }}/HutchAgent"
        state: "file"
        mode: u+x
# - name: Run Nexus, MinIO, Postgres, etc.
#   hosts: tre_server
#   tasks:
#     - name: Run Docker Compose
#       community.docker.docker_compose:
#         project_src: "{{ ansible_env.HOME }}/hutch"
#         project_name: hutch
#         files:
#           - docker-compose.yml
#       register: output
