name: Build Docs Website

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - website/**
      - .github/workflows/build.docs-website.yml

env:
  # Configure these
  CI_node-version: "16"
  CI_package: website

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.1.0
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.CI_node-version }}
          cache: pnpm
      - run: pnpm i --frozen-lockfile --filter ${{ env.CI_package }}
      - run: pnpm --filter ${{ env.CI_package }} build
