name: Publish Agent Docker

on:
  workflow_dispatch: # manual trigger
    inputs:
      buildConfig:
        description: Build Configuration
        required: true
        default: release
  push:
    # branches: [main]
    branches: [feature/agent-docker-CI]  # remove before merge to main

jobs:
  publish-agent-docker:
    runs-on: ubuntu-latest
    env:
      IMAGE: hutchagent:latest
      WORKDIR: ./app/HutchAgent
    outputs:
      artifact_name: ${{ env.IMAGE }}
    steps:
      - uses: actions/checkout@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.1.1
        with:
          push: false
          tags: ${{ env.IMAGE }}
          context: ${{ env.WORKDIR }}
      - name: Docker Image Artifact Upload
        uses: ishworkh/docker-image-artifact-upload@v1
        with:
          image: ${{ env.IMAGE }}
