name: Publish Agent Wheel

on:
  workflow_dispatch: # manual trigger
    inputs:
      buildConfig:
        description: Build Configuration
        required: true
        default: release
  push:
    # branches: [main, support/*]
    branches: [feature/agent-wheel-CI]  # remove this line when ready for merge to main

jobs:
  publish-wheel:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: "3.9"
      POETRY_VERSION: "1.1.14"
      WORKDIR: "./app/HutchAgent"
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install poetry
        working-directory: ${{ env.WORKDIR }}
        run: pip install poetry==${{ env.POETRY_VERSION }}
      - name: Install agent deps
        working-directory: ${{ env.WORKDIR }}
        run: poetry install --no-dev
      - name: Publish dist
        working-directory: ${{ env.WORKDIR }}
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: ["./hutchagent*.tar.gz", "./hutchagent*.whl"]
          tag: hutchagent



