name: Release Rquest OMOP Worker (stable)

on:
  workflow_dispatch: # manual trigger
    inputs:
      version_tag:
        description: Version tag
        required: true
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  get-version:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/worker-')
    runs-on: ubuntu-latest
    outputs:
      VERSION_TAG: ${{ steps.get-tag-auto.outputs.VERSION_TAG || steps.get-tag-manual.outputs.VERSION_TAG}}
    steps:
      - name: Get Version Tag
        id: get-tag-auto
        if: ${{ inputs.version_tag }} == ''
        run: |
          echo ::set-output name=VERSION_TAG::$(echo ${GITHUB_REF_NAME#release/rquest-omop-worker-})
      - name: Get Version Tag (manual)
        id: get-tag-manual
        if: ${{ inputs.version_tag }} != ''
        run: |
          echo ::set-output name=VERSION_TAG::${{ inputs.version_tag }}

  publish-worker-docker:
    needs: get-version
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      APP_NAME: rquest-omop-worker
      REGISTRY: hutchstack
    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.HUTCHSTACK_USER }}
          password: ${{ secrets.HUTCHSTACK_PASSWORD }}

      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.APP_NAME }}
          tags: |
            stable
            ${{ needs.get-version.outputs.VERSION_TAG }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.1.1
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: app/rquest-omop-worker/Dockerfile
