name: Release Agent (stable)

on:
  workflow_dispatch: # manual trigger
    inputs:
      version_tag:
        description: Version tag
        required: true
  pull_request:
    types:
      - closed
    branches:
      - release/**
    paths:
      - /app/HutchAgent/**

env:
  PYTHON_VERSION: "3.9"
  POETRY_VERSION: "1.1.14"
  WORKDIR: "./app/HutchAgent"

jobs:
  get-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    id: get-version
    steps:
      - name: Get Version Tag
        run: |
          echo ::set-output name=VERSION_TAG::$(echo $GITHUB_REF_NAME | cut -f 1 -d /)
  
  bump-version:
    needs: get-version
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VERSION }}
      - name: Bump Agent Version
        working-directory: ${{ env.WORKDIR }}
        run: |
          poetry version ${{ needs.get-version.outputs.VERSION_TAG }}

  publish-agent-wheel:
    needs: bump-version
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      RELEASE_NAME: agent-${{ inputs.version_tag }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VERSION }}
      - name: Install agent deps
        working-directory: ${{ env.WORKDIR }}
        run: poetry install --no-dev
      - name: Build dist
        working-directory: ${{ env.WORKDIR }}
        run: poetry build
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          prerelease: true
          files: |
            ${{ env.WORKDIR }}/dist/*
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.RELEASE_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true

  publish-agent-docker:
    needs: bump-version
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      APP_NAME: agent
      WORKDIR: ./app/HutchAgent
      VERSION_TAG: ${{ inputs.version_tag }}
      REGISTRY: ghcr.io
    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.APP_NAME }}
          tags: |
            stable
            ${{ env.VERSION_TAG }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.1.1
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          context: ${{ env.WORKDIR }}
