name: Bump Manager Version

on:
  workflow_dispatch: # manual trigger
    inputs:
      version_tag:
        description: Version tag
        required: true
  pull_request:
    types:
      - opened
    branches:
      - release/**
    paths:
      - /app/HutchManager/**
  

env:
  CI_build-config: release
  CI_dotnet-version: 6.0.x
  CI_node-version: "16"
  CI_publish-dir: publish

  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

jobs:
  get-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    id: get-version
    steps:
      - name: Get Version Tag
        if: ${{ input.version_tag }} == ''
        run: |
          echo ::set-output name=VERSION_TAG::$(echo $GITHUB_REF_NAME | cut -f 2 -d /)
      - name: Get Version Tag (manual)
        if: ${{ input.version_tag }} != ''
        run: |
          echo ::set-output name=VERSION_TAG::${{ input.version_tag }}
