name: Bump Agent Version

on:
  workflow_dispatch: # manual trigger
    inputs:
      version_tag:
        description: Version tag
        required: true
  # push:
  #   branches:
  #     - release/agent-**

env:
  PYTHON_VERSION: "3.9"
  POETRY_VERSION: "1.1.14"
  WORKDIR: "./app/HutchAgent"

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      VERSION_TAG: ${{ steps.get-tag-auto.outputs.VERSION_TAG || steps.get-tag-manual.outputs.VERSION_TAG}}
    steps:
      - name: Get Version Tag
        id: get-tag-auto
        if: ${{ input.version_tag }} == ''
        run: |
          echo ::set-output name=VERSION_TAG::$(echo ${GITHUB_REF_NAME#release/agent-})
      - name: Get Version Tag (manual)
        id: get-tag-manual
        if: ${{ input.version_tag }} != ''
        run: |
          echo ::set-output name=VERSION_TAG::${{ input.version_tag }}
  
  bump-version:
    needs: get-version
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VERSION }}
      - name: Bump Version
        working-directory: ${{ env.WORKDIR }}
        run: |
          poetry version ${{ needs.get-version.outputs.VERSION_TAG }}
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.0
        with:
          add: pyproject.toml
          cwd: ${{ env.WORKDIR }}
          message: bumped version to ${{ needs.get-version.outputs.VERSION_TAG }}

